#
#       Configuration File
#

Browser = Edge
# Options -> Chrome, FireFox, FFgeko, IE, Safari,  Edge

#Work Order Number to be used in finding customer.
WorkOrderNumber = 10165
# FirstName to be use in Searching 313761
FirstName = Randolph
# LastName to be use in Searching
LastName = Atlantic
# Phone Number to be use in Searching
PhoneNumber = (952) 426-6632
StockNumber = 8678
#StockNumber = 9046
#Stock Number to be used in searching.
CustomerNumber = 1999
#CustomerNumber = 1795

SendReportEmail = true
CompletedWithinDays = 30

Token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJFTXhSRVpHUVRnM1F6Z3lRMFExT1RWQlJrUTNOakF6UmpreE9UVXdOemhCTWtGRE1FUXdOUSJ9.eyJodHRwOi8vY29tX2lkc191c2VyaWQiOiJJLlVMTEFIIiwiaHR0cDovL2NvbV9pZHNfYWNjb3VudGlkIjoiNDg2IiwiaHR0cDovL2NvbV9pZHNfc2Vzc2lvbmlkIjoiMmE5YzQxOTgxZWQ4NDkwMThjMTBiMDc1MzVmZTJkNmQiLCJpc3MiOiJodHRwczovL2lkc2czYXBpLmF1dGgwLmNvbS8iLCJzdWIiOiIxMzZpYWVZR0xiYlB2SFVIZ1l5WWptQmRGa2xOYkxKekBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hdXRoMC5pZHNnM2FwaS5pbnRlZ3JhdGVkZGVhbGVyc3lzdGVtcy5jb20iLCJpYXQiOjE1OTUwMDY0MDIsImV4cCI6MTU5NTA5MjgwMiwiYXpwIjoiMTM2aWFlWUdMYmJQdkhVSGdZeVlqbUJkRmtsTmJMSnoiLCJzY29wZSI6ImFwaSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.NdpnEkIpm0dUioAE2ZqQx55lLoSFVDAqhw9UUb4UO9TLwSQzJxa-ANjNVwzEO0E7kdISVIxjwiXghnTe51KtNuaILFxMRfoglFWiX52zNlGxI6MHs-HAfpG1wexLQUN9l4EzMa1rTGh8DOQpkTmscWFSZWmzp7dTYpSGupKPu8Hs9e-QNETrXC4zRSr2Z7f4DbZWi6VeidsVUkAa_hPC9ebquaYj9nW1hfeGeOg5ptaw4R2gFRWsAH4AaVfMSlauMMn8idM1JptwgDhqKsDMr13ZJ2X8lwfrGuYJ9yYDMRJH2LUY9m9UMvxHDpbTda-oQfujTa5AMnKT-ej5DeKNVA
APIAddress = https://mbdev.integrateddealersystems.com/IDSG3WorkOrderApi/Service/v1/WorkOrders/Search

Location = RVK

UserID = i.ullah

#Email address for login.
Email = i.ullah@mbdev.com
#Email = i.ullah@mbdev.com
Password = P@ccw0rdJuly
# Domain Name of the given page
#Domain = https://g3qa559.integrateddealersystems.com/workorder/#/login
Domain = https://mbdev.integrateddealersystems.com/workorder/#/

Environment = IDS-DEV-VM50
# Options -> dev