#
#       Configuration File
#

Browser = Chrome
# Options -> Chrome, FireFox, FFgeko, IE, Safari,  Edge

#Work Order Number to be used in finding customer.
WorkOrderNumber = 10165
# FirstName to be use in Searching 313761
FirstName = Randolph
# LastName to be use in Searching
LastName = Atlantic
# Phone Number to be use in Searching
PhoneNumber = (952) 426-6632
StockNumber = 8678
#StockNumber = 9046
#Stock Number to be used in searching.
CustomerNumber = 1999
#CustomerNumber = 1795

SendReportEmail = true
CompletedWithinDays = 30

Token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJFTXhSRVpHUVRnM1F6Z3lRMFExT1RWQlJrUTNOakF6UmpreE9UVXdOemhCTWtGRE1FUXdOUSJ9.eyJodHRwOi8vY29tX2lkc191c2VyaWQiOiJJLlVMTEFIIiwiaHR0cDovL2NvbV9pZHNfYWNjb3VudGlkIjoiNTU5IiwiaHR0cDovL2NvbV9pZHNfc2Vzc2lvbmlkIjoiNzE5NWViZjI5MTkxNDcyMWE5NTgyN2ZkNjg1ZjMxYWYiLCJpc3MiOiJodHRwczovL2lkc2czYXBpLmF1dGgwLmNvbS8iLCJzdWIiOiJqMEFFOE9qMDROWXQ1cHB4bHZiQkhqRGg1amR3ZDFlbEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hdXRoMC5pZHNnM2FwaS5pbnRlZ3JhdGVkZGVhbGVyc3lzdGVtcy5jb20iLCJpYXQiOjE1OTU4MzY1MzUsImV4cCI6MTU5NTkyMjkzNSwiYXpwIjoiajBBRThPajA0Tll0NXBweGx2YkJIakRoNWpkd2QxZWwiLCJzY29wZSI6ImFwaSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.Qs4TKX1oRJv2YDnGgqNxgyHQluR9zhOmPud1JWICNYaAbXe6PhZvDdaRaX6OCCtwDfluG5vXOC3ntHZU_-46WmYvL8-ecx7f3wFpLP4HtFmyLUf3Raaq11OgcS_dzQzd2BgBxwBuyov6tmO4vBAMUjlipBTfnO3nw4fk0uUVD2sdyQ8pEM-C8pxtvl3Qqam-uA9kKmW5_1o7R85CoIanVbBXJSQ23dkaP9kwguWVkBNsNzQuPY7CtVk_grkO6HwYtEo_ETMraWONUb6enB1JDACUOyhhpBjNS07vgtlAzOS6gI7lZWx--1LIKJSLWYwVs2zhNCtW--U9QmqVcEyCYA
APIAddress = https://mbdev.integrateddealersystems.com/IDSG3WorkOrderApi/Service/v1/WorkOrders/Search

Location = RVK

UserID = i.ullah

#Email address for login.
Email = i.ullah@mbdev.com
#Email = i.ullah@mbdev.com
Password = P@ccw0rdJuly
# Domain Name of the given page
#Domain = https://g3qa559.integrateddealersystems.com/workorder/#/login
Domain = https://mbdev.integrateddealersystems.com/workorder/#/

Environment = IDS-DEV-VM50
# Options -> dev