#
#       Configuration File
#

Browser = Chrome
# Options -> Chrome, FireFox, FFgeko, IE, Safari,  Edge

#Work Order Number to be used in finding customer. 2729
WorkOrderNumber = 2729


# FirstName to be use in Searching 313761
FirstName = Lucy
# LastName to be use in Searching
LastName = BALL
# Phone Number to be use in Searching
PhoneNumber = 727-937-0555
StockNumber = 1637
#StockNumber = 9046
#Stock Number to be used in searching.
CustomerNumber = 1023
#CustomerNumber = 1795

SendReportEmail = false
#true, false
ToEmailAddress = i.ullah@ids-astra.com
CCEmailAddress = idsastraqa3@gmail.com,idsastraqa4@gmail.com
CompletedWithinDays = 30

APIBaseURL = https://g3qa559.integrateddealersystems.com/IDSG3WorkOrderApi
EncryptedPassword = mb1HL3x+2Y9DegDA5UndxQ==
Location = SMC

UserID = i.ullah

#Email address for login.
Email = i.ullah@ids-qa-vm94.com
#Email = i.ullah@mbdev.com
Password = P@ccw0rdSep20
# Domain Name of the given page
Domain = https://g3qa559.integrateddealersystems.com/g3/#/login
#Domain = https://mbdev.integrateddealersystems.com/workorder/#/

Environment = IDS-QA-VM94
# Options -> dev

U2RestApiBaseUrl = https://g3qa559.integrateddealersystems.com/IDSU2RestAPI/
U2RestApiToken = PD%!^;PkJ#F8]6YQ
AccountID = 559