#
#       Configuration File
#

Browser = Chrome
# Options -> Chrome, FireFox, FFgeko, IE, Safari,  Edge

#Work Order Number to be used in finding customer.
WorkOrderNumber = 3000
# FirstName to be use in Searching 313761
FirstName = LUCY
# LastName to be use in Searching
LastName = BALL
# Phone Number to be use in Searching
PhoneNumber = 03444442935
StockNumber = 1637
#StockNumber = 9046
#Stock Number to be used in searching.
CustomerNumber = 1023
#CustomerNumber = 1795

CompletedWithinDays = 30

Token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJFTXhSRVpHUVRnM1F6Z3lRMFExT1RWQlJrUTNOakF6UmpreE9UVXdOemhCTWtGRE1FUXdOUSJ9.eyJodHRwOi8vY29tX2lkc191c2VyaWQiOiJJLlVMTEFIIiwiaHR0cDovL2NvbV9pZHNfYWNjb3VudGlkIjoiNTU5IiwiaHR0cDovL2NvbV9pZHNfc2Vzc2lvbmlkIjoiMDYyNWVhYjhhZmRmNGQ0M2I5NjI3ZGVkZGZhNzkzMDYiLCJpc3MiOiJodHRwczovL2lkc2czYXBpLmF1dGgwLmNvbS8iLCJzdWIiOiJqMEFFOE9qMDROWXQ1cHB4bHZiQkhqRGg1amR3ZDFlbEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hdXRoMC5pZHNnM2FwaS5pbnRlZ3JhdGVkZGVhbGVyc3lzdGVtcy5jb20iLCJpYXQiOjE1OTQ0ODk2NTEsImV4cCI6MTU5NDU3NjA1MSwiYXpwIjoiajBBRThPajA0Tll0NXBweGx2YkJIakRoNWpkd2QxZWwiLCJzY29wZSI6ImFwaSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.MMezvhkpFZ24O6hWGe5Mqzud-hshyC9RQvQoxNjgOKOE51LtMVQKp7HyDU-Pv0GfROWB9e1Jwv95mVa84B2-VfxdrpaN8ZREDkggNgjQKynL_HDzV03140y5ant4rB3gvC-WAR0f8QMuzgEN2fGrrQG9YFz6nAwCsT-7OwqDQw7ekloiOnLtpfEIEFcdvz3JceoM3tseLqNf6FDUEVTJv0E9tXHn6Zz2T_dtiv1yC4mK_lPxFJ15Zx68SOrqRkTMYolIKgzv4BEuoEMrSd9bIGr-D2vVnNwHZwcKAFzdX7Ym90Fu1VzkXCCZ_Q_IQjs6KOpEOb3GADziycttO7WKLA
APIAddress = https://g3qa559.integrateddealersystems.com/IDSG3WorkOrderApi/Service/v1/WorkOrders/Search

Location = SMC

UserID = i.ullah

#Email address for login.
Email = i.ullah@ids-qa-vm94.com
#Email = i.ullah@mbdev.com
Password = P@ccw0rdJuly
# Domain Name of the given page
Domain = https://g3qa559.integrateddealersystems.com/workorder/#/login
#Domain = https://mbdev.integrateddealersystems.com/workorder/#/

Environment = IDS-QA-VM94
# Options -> dev