#
#       Configuration File
#

Browser = Chrome
# Options -> Chrome, FireFox, FFgeko, IE, Safari,  Edge

#Work Order Number to be used in finding customer.
WorkOrderNumber = 313761
# FirstName to be use in Searching 313761
FirstName = Mueller
# LastName to be use in Searching
LastName = Sexton
# Phone Number to be use in Searching
PhoneNumber = 3444442935


StockNumber = 327684
#Stock Number to be used in searching.
CustomerNumber = 196343
#Stock Number to be used in searching.

# Domain Name of the given page
Domain = https://mbdev.integrateddealersystems.com/workorder/#/

Environment = IDS-QA-VM083
# Options -> dev