#
#       Configuration File
#

Browser = Chrome
# Options -> Chrome, FireFox, FFgeko, IE, Safari,  Edge

#Work Order Number to be used in finding customer.
WorkOrderNumber = 313761
# FirstName to be use in Searching 313761
FirstName = Marek
# LastName to be use in Searching
LastName = Irfan
# Phone Number to be use in Searching
PhoneNumber = 3444442935
# Domain Name of the given page

StockNumber = 595662
#Stock Number to be used in searching.
CustomerNumber = 932651
#Stock Number to be used in searching.


Domain = https://mbdev.integrateddealersystems.com/workorder/#/

Environment = IDS-QA-VM083
# Options -> dev