#
#       Configuration File
#

Browser = Chrome
# Options -> Chrome, FireFox, FFgeko, IE, Safari & Edge

WorkOrderNumber = 61124

# FirstName to be use in Searching
FirstName = Smith
# LastName to be use in Searching
LastName = Irfan
# Phone Number to be use in Searching
PhoneNumber = 3444442935
# Domain Name of the given page
Domain = https://mbdev.integrateddealersystems.com/workorder/#/

Environment = IDS-QA-VM083
# Options -> dev