#
#       Configuration File
#

Browser = FireFox
# Options -> Chrome, FireFox, FFgeko, IE, Safari,  Edge

#Work Order Number to be used in finding customer.
WorkOrderNumber = 10165
# FirstName to be use in Searching 313761
FirstName = Randolph
# LastName to be use in Searching
LastName = Atlantic
# Phone Number to be use in Searching
PhoneNumber = (952) 426-6632
StockNumber = 8678
#StockNumber = 9046
#Stock Number to be used in searching.
CustomerNumber = 1999
#CustomerNumber = 1795

SendReportEmail = false
CompletedWithinDays = 30

APIBaseURL = https://mbdev.integrateddealersystems.com/IDSG3WorkOrderApi
EncryptedPassword = mb1HL3x+2Y9DegDA5UndxQ==

Location = RVK

UserID = i.ullah

#Email address for login.
Email = i.ullah
#Email = i.ullah@mbdev.com
Password = P@ccw0rdSep20
# Domain Name of the given page
#Domain = https://g3qa559.integrateddealersystems.com/workorder/#/login
Domain = https://mbdev.integrateddealersystems.com/workorder/#/

Environment = IDS-DEV-VM50
# Options -> dev

U2RestApiBaseUrl = https://mbdev.integrateddealersystems.com/IDSU2RestAPI/
U2RestApiToken = PD%!^;PkJ#F8]6YQ
AccountID = 486