#
#       Configuration File
#

Browser = Chrome
# Options -> Chrome, FireFox, FFgeko, IE, Safari,  Edge

#Work Order Number to be used in finding customer.
WorkOrderNumber = 3000
# FirstName to be use in Searching 313761
FirstName = Lucy
# LastName to be use in Searching
LastName = BALL
# Phone Number to be use in Searching
PhoneNumber = 03444442935
StockNumber = 1637
#StockNumber = 9046
#Stock Number to be used in searching.
CustomerNumber = 1023
#CustomerNumber = 1795

CompletedWithinDays = 30

Token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJFTXhSRVpHUVRnM1F6Z3lRMFExT1RWQlJrUTNOakF6UmpreE9UVXdOemhCTWtGRE1FUXdOUSJ9.eyJodHRwOi8vY29tX2lkc191c2VyaWQiOiJJLlVMTEFIIiwiaHR0cDovL2NvbV9pZHNfYWNjb3VudGlkIjoiNTU5IiwiaHR0cDovL2NvbV9pZHNfc2Vzc2lvbmlkIjoiZDNiNWY4MWM3NzBiNGM1MDkwN2IzNzY2ZjYwYzg0M2EiLCJpc3MiOiJodHRwczovL2lkc2czYXBpLmF1dGgwLmNvbS8iLCJzdWIiOiJqMEFFOE9qMDROWXQ1cHB4bHZiQkhqRGg1amR3ZDFlbEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hdXRoMC5pZHNnM2FwaS5pbnRlZ3JhdGVkZGVhbGVyc3lzdGVtcy5jb20iLCJpYXQiOjE1OTQ2MDEyMjQsImV4cCI6MTU5NDY4NzYyNCwiYXpwIjoiajBBRThPajA0Tll0NXBweGx2YkJIakRoNWpkd2QxZWwiLCJzY29wZSI6ImFwaSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.ixL33_khnW-6jW4RZYCr1qQ6daQJR80Tvp176cRg59HpB61ZgKDYD-3rzUvW7SQZ7-KB_GfrJAyZ1gucpJSZeCcigi3klwSf_6vUOHUoFi-sj9wXS-fBSVeb9HVbBrCwprXDrPbCggLUhXwBMt68k8l9gyCfUAwGhwCHnjd_xq_d0YO7vYi3JDSIPwyK9i66xA_fpH0VAAwVrl1PiSN_ft98zgZSdDKEJ5yO3jjWvKVY6LzHXJSb34rAYnTW9bmjDH_qW8rrZlOz0RV1WTHSUU8fNkAfy4joq4TfAC81K4JKhqOwDwdnOXPWNLN--7bSBKNt1q22VxfkZ8yK89KwWw
  APIAddress = https://g3qa559.integrateddealersystems.com/IDSG3WorkOrderApi/Service/v1/WorkOrders/Search

Location = SMC

UserID = i.ullah

#Email address for login.
Email = i.ullah@ids-qa-vm94.com
#Email = i.ullah@mbdev.com
Password = P@ccw0rdJuly
# Domain Name of the given page
Domain = https://g3qa559.integrateddealersystems.com/workorder/#/login
#Domain = https://mbdev.integrateddealersystems.com/workorder/#/

Environment = IDS-QA-VM94
# Options -> dev