#
#       Configuration File
#

Browser = Chrome
# Options -> Chrome, FireFox, FFgeko, IE, Safari,  Edge

#Work Order Number to be used in finding customer.
WorkOrderNumber = 2729
# FirstName to be use in Searching 313761
FirstName = Lucy
# LastName to be use in Searching
LastName = BALL
# Phone Number to be use in Searching
PhoneNumber = 727-937-0555
StockNumber = 1637
#StockNumber = 9046
#Stock Number to be used in searching.
CustomerNumber = 1023
#CustomerNumber = 1795

SendReportEmail = true
#true, false
ToEmailAddress = i.ullah@ids-astra.com
CCEmailAddress = idsqateam@ids-astra.com
#CCEmailAddress = idsastraqa3@gmail.com,idsastraqa4@gmail.com
CompletedWithinDays = 30

Token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJFTXhSRVpHUVRnM1F6Z3lRMFExT1RWQlJrUTNOakF6UmpreE9UVXdOemhCTWtGRE1FUXdOUSJ9.eyJodHRwOi8vY29tX2lkc191c2VyaWQiOiJJLlVMTEFIIiwiaHR0cDovL2NvbV9pZHNfYWNjb3VudGlkIjoiNTU5IiwiaHR0cDovL2NvbV9pZHNfc2Vzc2lvbmlkIjoiZDdhMWU3NjhhYzkzNDRjYmE3MzIxNWZjN2JiNDM0NDgiLCJpc3MiOiJodHRwczovL2lkc2czYXBpLmF1dGgwLmNvbS8iLCJzdWIiOiJqMEFFOE9qMDROWXQ1cHB4bHZiQkhqRGg1amR3ZDFlbEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hdXRoMC5pZHNnM2FwaS5pbnRlZ3JhdGVkZGVhbGVyc3lzdGVtcy5jb20iLCJpYXQiOjE1OTUyMzI0MzUsImV4cCI6MTU5NTMxODgzNSwiYXpwIjoiajBBRThPajA0Tll0NXBweGx2YkJIakRoNWpkd2QxZWwiLCJzY29wZSI6ImFwaSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.c7Kbu7ITJo-5CbZRsNQbehzquEyWs9zlI3NO9e1SbLYNiujK3QAXtOwApFWE4nM32LsCiU4BZlYsFxz4uWKMKCjcQYvqwlTt3myDmIiG1Kg4ZnQp8RNk9XNIacOiIEnKCyBJtQF5l3cGk9OypGGEM-J6BgpOcLI9kMBrsQfRUf2CrK8Pc14L2u7A3BHdOlzC7eaHawzEZSPwlP5dSwp6bvhO7O5zqRYj80NjyxGFoAjDhxZwzbflP79EXH6OONFl5kAMvkcU0d0zVQHj29E2LTSBVejzQqtw8AC6dyYkSVMixTrNz8J4cDlUWzbyerk5dYoAFERITuCPIg5mXs0A7A
APIAddress = https://g3qa559.integrateddealersystems.com/IDSG3WorkOrderApi/Service/v1/WorkOrders/Search

Location = SMC

UserID = i.ullah

#Email address for login.
Email = i.ullah@ids-qa-vm94.com
#Email = i.ullah@mbdev.com
Password = P@ccw0rdJuly
# Domain Name of the given page
Domain = https://g3qa559.integrateddealersystems.com/workorder/#/login
#Domain = https://mbdev.integrateddealersystems.com/workorder/#/

Environment = IDS-QA-VM94
# Options -> dev