#
#       Configuration File
#

Browser = Chrome
# Options -> Chrome, FireFox, FFgeko, IE, Safari,  Edge

#Work Order Number to be used in finding customer.
WorkOrderNumber = 3000
# FirstName to be use in Searching 313761
FirstName = David
# LastName to be use in Searching
LastName = Ball
# Phone Number to be use in Searching
PhoneNumber = 3444442935
StockNumber = 9682
#StockNumber = 9046
#Stock Number to be used in searching.
CustomerNumber = 1401
#CustomerNumber = 1795

CompletedWithinDays = 30

Token = eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IlJFTXhSRVpHUVRnM1F6Z3lRMFExT1RWQlJrUTNOakF6UmpreE9UVXdOemhCTWtGRE1FUXdOUSJ9.eyJodHRwOi8vY29tX2lkc191c2VyaWQiOiJJLlVMTEFIIiwiaHR0cDovL2NvbV9pZHNfYWNjb3VudGlkIjoiNTU5IiwiaHR0cDovL2NvbV9pZHNfc2Vzc2lvbmlkIjoiOThjYTNhMjU5ZjczNGI2ZTg3OGRjZjdjZTViNzc0ZjUiLCJpc3MiOiJodHRwczovL2lkc2czYXBpLmF1dGgwLmNvbS8iLCJzdWIiOiJqMEFFOE9qMDROWXQ1cHB4bHZiQkhqRGg1amR3ZDFlbEBjbGllbnRzIiwiYXVkIjoiaHR0cHM6Ly9hdXRoMC5pZHNnM2FwaS5pbnRlZ3JhdGVkZGVhbGVyc3lzdGVtcy5jb20iLCJpYXQiOjE1OTM2ODk0MzEsImV4cCI6MTU5Mzc3NTgzMSwiYXpwIjoiajBBRThPajA0Tll0NXBweGx2YkJIakRoNWpkd2QxZWwiLCJzY29wZSI6ImFwaSIsImd0eSI6ImNsaWVudC1jcmVkZW50aWFscyJ9.MxX6LchjX7n67V12yay3-2F2mpiiMV-tOJTh2Yed5K9noLsQaV1Hx0CPJPzPfRNHMOSX5lPjl3D7Nn5FkroMPdDLWlyq7atBe6S1K4zPe2nzCDK0OzuRHitfC3Dy3TasL59pF6EFh93ekya8RFe79K6iUZBWLXXh2_PRJnS3QheP36y-JDYe1gEC-BP8NLPH83PKt1hgsJkIYaEuDsY-oXq0S25vAy5B71b4R5kCV48SJ3ahwOrEqZjAyw0LcMw1kh-VlzUII27l015wNxYWSryuEOncdcZ9FL6Q9pW4H2JvwTduz0B8pLvcJgsoVwrEpBjtHHXGo9plj1CPNKx4Dg

Location = SMC

#Email address for login.
Email = i.ullah@ids-qa-vm94.com
#Email = i.ullah@mbdev.com
Password = P@ccw0rdJune
# Domain Name of the given page
Domain = https://g3qa559.integrateddealersystems.com/g3login/#/login
#Domain = https://mbdev.integrateddealersystems.com/workorder/#/

Environment = IDS-QA-VM94
# Options -> dev